spring:
  application:
    name: spring-jpa
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: boot
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true